const express = require("express");
const morgan = require("morgan");
const employeeRouter = require("./routes/employeRoutes");
const assetRouter = require("./routes/assetsRoutes");
const bankRouter = require("./routes/bankRouter");
const holidayRouter = require("./routes/holidayRoutes");
const timeSheetRouter = require("./routes/timesheetRoutes");
const leavesRouter = require("./routes/leavesRoutes");
const employeeLeavesRouter = require("./routes/emplyoeeLeavesRoutes");
const leaveRequestRouter = require("./routes/emplyoeeLeaveRequestRouter");
const bodyParser = require("body-parser");
const multer = require("multer");
const cors = require("cors");
const app = express();
app.use(morgan("dev"));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(express.static("uploads"));
app.use(cors());
app.use("/uploads", express.static("uploads"));
app.use("/api/v1/employee", employeeRouter);
app.use("/api/v1/assets", assetRouter);
app.use("/api/v1/bank", bankRouter);
app.use("/api/v1/holidays", holidayRouter);
app.use("/api/v1/timesheet", timeSheetRouter);
app.use("/api/v1", leavesRouter);
app.use("/api/v1", employeeLeavesRouter);
app.use("/api/v1", leaveRequestRouter);
module.exports = app;
